name: ds_ads
description: Ads SectDev components for Flutter projects (https://sect.dev/). Supports AdMob and AppLovin mediations
version: 1.0.3
repository: https://github.com/al-tush/ds_ads

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  fimber: ^0.7.0
  # ds_common: ^1.0.3
  ds_common:
    git:
      url: https://github.com/ale-getman/ds_common.git
      ref: deferred_link
    # path: /Users/ag/Documents/devsect/ds_common/ds_common
  freezed_annotation: ^2.1.0
  collection: ^1.16.0

  google_mobile_ads: ^5.1.0

  applovin_max: 3.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: pro.altush.ads.ds_ads
        pluginClass: DsAdsPlugin
